# Generated by Django 5.1.3 on 2024-12-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
