# Generated by Django 5.1.3 on 2024-12-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_popularevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularevent',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
